[package]
name = "world_dispatcher"
version = "0.100.1"
authors = ["Joël Lupien (Jojolepro) <jojolepro@jojolepro.com>"]
edition = "2018"
description = "Provides the System part of a full ECS, along with a fast dispatcher and world container."
keywords = ["game", "ecs"]
categories = ["game-engines"]
license = "AGPL-3.0-only"
exclude = ["doc"]
repository = "https://git.jojolepro.com/world_dispatcher/"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
profiler = ["thread_profiler", "thread_profiler/thread_profiler"]
parallel = ["rayon"]
big_systems = []

[dependencies]
downcast-rs = "1.2"
derive-new = "0.5.8"
rayon = { version = "1.4.0", optional = true }
thread_profiler = { version = "0.3.0", optional = true }

[dev-dependencies]
wasm-bindgen-test = "0.3"
