[package]
name = "world_dispatcher"
version = "0.1.0"
authors = ["Joël Lupien (Jojolepro) <jojolepro@jojolepro.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
profiler = ["thread_profiler", "thread_profiler/thread_profiler"]
parallel = ["rayon"]

[dependencies]
downcast-rs = "1.2"
derive-new = "0.5.8"
rayon = { version = "1.4.0", optional = true }
thread_profiler = { version = "0.3.0", optional = true }

